version: '3'

services:

  devenv:
    image: registry.obvsg.at/primo/frontend/primo-explore-devenv-docker
    environment:
      PROXY_SERVER: https://search-test.obvsg.at:443 # replace with url to your primo instance
      VIEW: OBV # replace with name of your view as it appears below in "volumes"
      GULP_OPTIONS: "--browserify"
    ports:
      - 8003:8003 # used to view the application
      - 3001:3001 # used to view the browsersync dashboard
    volumes:
      - ./:/app/primo-explore-devenv/packages # used to access generated package .zip files
      - /home/primo/primo-explore-obv:/app/primo-explore-devenv/primo-explore/custom/OBV # replace with path to your view folder
      - /home/primo/primo-explore-obv-central:/app/primo-explore-devenv/primo-explore/custom/CENTRAL_PACKAGE # optional - replace with path to your central package folder
